name: nest_ui
version: 0.1.0
description: >
  A Dart implementation of the NestUI concept. Basically, a UI framework with nestable components.
author: Roman Snitko <roman.snitko@gmail.com>
homepage: http://nestui.romansnitko.com
documentation: http://nestui.romansnitko.com/docs

dependencies:
  observable_roles:
    path: '../observable_roles'
  heritage_tree:
    path: '../heritage_tree'
  attributable:
    path: '../attributable'
  validatable:
    path: '../validatable'
  logmaster:
    path: '../logmaster'

dev_dependencies:
  test: '>=0.12.0'

dependency_overrides:
