name: nest_ui
version: 0.6.7
description: >
  A Dart implementation of the NestUI concept. Basically, a UI framework with nestable components.
author: Roman Snitko <roman.snitko@gmail.com>
homepage: http://nestui.romansnitko.com
documentation: http://nestui.romansnitko.com

dependencies:
  observable_roles: '>=0.1.3 <0.2.0'
  heritage_tree: '>=0.1.0 <0.2.0'
  attributable: '>=0.1.1 <0.2.0'
  validatable: '>=0.1.2 <0.2.0'
  logmaster: '>=0.1.1 <0.2.0'
  queries: '>=0.1.1 <0.2.0'
  cookie: '>=0.0.4 <0.0.5'
  animation: '>=0.5.24 <0.6.0'

dev_dependencies:
  test: '>=0.12.0'
  mockito: '>=0.11.0'

dependency_overrides:
  attributable:
    path: "../attributable"
