name: dartifact
version: 0.6.85
description: >
  a Web-UI framework with nestable components.
author: Roman Snitko <roman.snitko@gmail.com>
homepage: http://dartifact.org
documentation: http://dartifact.org

dependencies:
  observable_roles: '>=0.1.43 <0.2.0'
  heritage_tree: '>=0.1.0 <0.2.0'
  attributable: '>=0.1.1 <0.2.0'
  validatable: '>=0.1.2 <0.2.0'
  logmaster: '>=0.1.1 <0.2.0'
  queries: '>=0.0.15 <0.5.0'
  cookie: '>=0.0.4 <0.0.5'
  animation: '>=0.5.24 <0.6.0'

dev_dependencies:
  test: '>=0.12.0'
  mockito: '>=0.11.0'

#dependency_overrides:
  #observable_roles:
    #path: "../observable_roles"
